title: "面试题库"
description: "程序员面试题目收集与整理"
baseurl: "/Questions"
url: "https://xzonn.top"

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    css_class: highlight
highlighter: rouge
plugins:
  - jekyll-algolia
  - jekyll-archives
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-sitemap

collections:
  posts:
    output: true
    permalink: /:collection/:path.html

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "question"

sass:
  style: compressed

paginate: 12
paginate_path: "/pages/:num/"

jekyll-archives:
  layout: category
  enabled: 
    - categories
  permalinks:
    category: "/category/:name.html"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - Debug/
  - venv/
  - README.md

algolia:
  application_id: "5QVIJPXEHT"
  index_name: "interview_questions"
  search_only_api_key: "148f2d0a222861b72fc1b3afed298ecd"
  powered_by: true
  files_to_exclude:
    - index.html
    - categories.html
    - search.html
    - category/
    - pages/
  settings:
    hitsPerPage: 10
    searchableAttributes:
      - title
      - excerpt
      - content
      - category
      - unordered(tags)
      - unordered(content)
    attributesToHighlight:
      - title
      - tags
      - content
    attributesForFaceting:
      - unordered(tags)
      - title
    customRanking:
      - 'desc(date)'
